package com.riux.spring.entities;
// Generated 26-jul-2017 13:11:43 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TdCompra generated by hbm2java
 */
public class TdCompra implements java.io.Serializable {

	private Integer id;
	private TdUsuario tdUsuario;
	private Integer cantidad;
	private BigDecimal preciototal;
	private Set tdDetalleCompras = new HashSet(0);

	public TdCompra() {
	}

	public TdCompra(TdUsuario tdUsuario) {
		this.tdUsuario = tdUsuario;
	}

	public TdCompra(TdUsuario tdUsuario, Integer cantidad, BigDecimal preciototal, Set tdDetalleCompras) {
		this.tdUsuario = tdUsuario;
		this.cantidad = cantidad;
		this.preciototal = preciototal;
		this.tdDetalleCompras = tdDetalleCompras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TdUsuario getTdUsuario() {
		return this.tdUsuario;
	}

	public void setTdUsuario(TdUsuario tdUsuario) {
		this.tdUsuario = tdUsuario;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPreciototal() {
		return this.preciototal;
	}

	public void setPreciototal(BigDecimal preciototal) {
		this.preciototal = preciototal;
	}

	public Set getTdDetalleCompras() {
		return this.tdDetalleCompras;
	}

	public void setTdDetalleCompras(Set tdDetalleCompras) {
		this.tdDetalleCompras = tdDetalleCompras;
	}

}
