package com.riux.spring.entities;
// Generated 26-jul-2017 13:11:43 by Hibernate Tools 5.2.3.Final

/**
 * TdDetalleProducto generated by hbm2java
 */
public class TdDetalleProducto implements java.io.Serializable {

	private Integer id;
	private TdProducto tdProducto;
	private String imagenUrl;
	private boolean estado;
	private String descripcion;

	public TdDetalleProducto() {
	}

	public TdDetalleProducto(TdProducto tdProducto, boolean estado) {
		this.tdProducto = tdProducto;
		this.estado = estado;
	}

	public TdDetalleProducto(TdProducto tdProducto, String imagenUrl, boolean estado, String descripcion) {
		this.tdProducto = tdProducto;
		this.imagenUrl = imagenUrl;
		this.estado = estado;
		this.descripcion = descripcion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TdProducto getTdProducto() {
		return this.tdProducto;
	}

	public void setTdProducto(TdProducto tdProducto) {
		this.tdProducto = tdProducto;
	}

	public String getImagenUrl() {
		return this.imagenUrl;
	}

	public void setImagenUrl(String imagenUrl) {
		this.imagenUrl = imagenUrl;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
