package com.riux.spring.entities;
// Generated 26-jul-2017 13:11:43 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TdPersona generated by hbm2java
 */
public class TdPersona implements java.io.Serializable {

	private Integer id;
	private TdUsuario tdUsuario;
	private boolean estado;
	private Date fechaRegistro;
	private String nombres;
	private String apePaterno;
	private String apeMaterno;
	private String direccion;
	private Date fecNacimiento;
	private String genero;

	public TdPersona() {
	}

	public TdPersona(TdUsuario tdUsuario, boolean estado, Date fechaRegistro, String nombres, String apePaterno,
			String apeMaterno, Date fecNacimiento, String genero) {
		this.tdUsuario = tdUsuario;
		this.estado = estado;
		this.fechaRegistro = fechaRegistro;
		this.nombres = nombres;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.fecNacimiento = fecNacimiento;
		this.genero = genero;
	}

	public TdPersona(TdUsuario tdUsuario, boolean estado, Date fechaRegistro, String nombres, String apePaterno,
			String apeMaterno, String direccion, Date fecNacimiento, String genero) {
		this.tdUsuario = tdUsuario;
		this.estado = estado;
		this.fechaRegistro = fechaRegistro;
		this.nombres = nombres;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.direccion = direccion;
		this.fecNacimiento = fecNacimiento;
		this.genero = genero;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TdUsuario getTdUsuario() {
		return this.tdUsuario;
	}

	public void setTdUsuario(TdUsuario tdUsuario) {
		this.tdUsuario = tdUsuario;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApePaterno() {
		return this.apePaterno;
	}

	public void setApePaterno(String apePaterno) {
		this.apePaterno = apePaterno;
	}

	public String getApeMaterno() {
		return this.apeMaterno;
	}

	public void setApeMaterno(String apeMaterno) {
		this.apeMaterno = apeMaterno;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

}
