package com.riux.spring.entities;
// Generated 26-jul-2017 13:11:43 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TdProducto generated by hbm2java
 */
public class TdProducto implements java.io.Serializable {

	private Integer id;
	private TdCategoriaProducto tdCategoriaProducto;
	private String pronom;
	private boolean proest;
	private String propre;
	private Set tdDetalleCompras = new HashSet(0);
	private Set tdDetalleProductos = new HashSet(0);

	public TdProducto() {
	}

	public TdProducto(TdCategoriaProducto tdCategoriaProducto, String pronom, boolean proest, String propre) {
		this.tdCategoriaProducto = tdCategoriaProducto;
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
	}

	public TdProducto(TdCategoriaProducto tdCategoriaProducto, String pronom, boolean proest, String propre,
			Set tdDetalleCompras, Set tdDetalleProductos) {
		this.tdCategoriaProducto = tdCategoriaProducto;
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
		this.tdDetalleCompras = tdDetalleCompras;
		this.tdDetalleProductos = tdDetalleProductos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TdCategoriaProducto getTdCategoriaProducto() {
		return this.tdCategoriaProducto;
	}

	public void setTdCategoriaProducto(TdCategoriaProducto tdCategoriaProducto) {
		this.tdCategoriaProducto = tdCategoriaProducto;
	}

	public String getPronom() {
		return this.pronom;
	}

	public void setPronom(String pronom) {
		this.pronom = pronom;
	}

	public boolean isProest() {
		return this.proest;
	}

	public void setProest(boolean proest) {
		this.proest = proest;
	}

	public String getPropre() {
		return this.propre;
	}

	public void setPropre(String propre) {
		this.propre = propre;
	}

	public Set getTdDetalleCompras() {
		return this.tdDetalleCompras;
	}

	public void setTdDetalleCompras(Set tdDetalleCompras) {
		this.tdDetalleCompras = tdDetalleCompras;
	}

	public Set getTdDetalleProductos() {
		return this.tdDetalleProductos;
	}

	public void setTdDetalleProductos(Set tdDetalleProductos) {
		this.tdDetalleProductos = tdDetalleProductos;
	}

}
