package com.riux.spring.entities;
// Generated 26-jul-2017 13:11:43 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

/**
 * TdPunto generated by hbm2java
 */
public class TdPunto implements java.io.Serializable {

	private Integer id;
	private TdUsuario tdUsuario;
	private BigDecimal puntos;

	public TdPunto() {
	}

	public TdPunto(TdUsuario tdUsuario) {
		this.tdUsuario = tdUsuario;
	}

	public TdPunto(TdUsuario tdUsuario, BigDecimal puntos) {
		this.tdUsuario = tdUsuario;
		this.puntos = puntos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TdUsuario getTdUsuario() {
		return this.tdUsuario;
	}

	public void setTdUsuario(TdUsuario tdUsuario) {
		this.tdUsuario = tdUsuario;
	}

	public BigDecimal getPuntos() {
		return this.puntos;
	}

	public void setPuntos(BigDecimal puntos) {
		this.puntos = puntos;
	}

}
