package com.riux.spring.entities;
// Generated 26-jul-2017 13:11:43 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TdUsuario generated by hbm2java
 */
public class TdUsuario implements java.io.Serializable {

	private Integer id;
	private TeRol teRol;
	private String nombreUsuario;
	private String contrasenia;
	private boolean estado;
	private String cuecorele;
	private Set tdPersonas = new HashSet(0);
	private Set tdPuntos = new HashSet(0);
	private Set tdCompras = new HashSet(0);

	public TdUsuario() {
	}

	public TdUsuario(TeRol teRol, String nombreUsuario, String contrasenia, boolean estado) {
		this.teRol = teRol;
		this.nombreUsuario = nombreUsuario;
		this.contrasenia = contrasenia;
		this.estado = estado;
	}

	public TdUsuario(TeRol teRol, String nombreUsuario, String contrasenia, boolean estado, String cuecorele,
			Set tdPersonas, Set tdPuntos, Set tdCompras) {
		this.teRol = teRol;
		this.nombreUsuario = nombreUsuario;
		this.contrasenia = contrasenia;
		this.estado = estado;
		this.cuecorele = cuecorele;
		this.tdPersonas = tdPersonas;
		this.tdPuntos = tdPuntos;
		this.tdCompras = tdCompras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TeRol getTeRol() {
		return this.teRol;
	}

	public void setTeRol(TeRol teRol) {
		this.teRol = teRol;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public String getCuecorele() {
		return this.cuecorele;
	}

	public void setCuecorele(String cuecorele) {
		this.cuecorele = cuecorele;
	}

	public Set getTdPersonas() {
		return this.tdPersonas;
	}

	public void setTdPersonas(Set tdPersonas) {
		this.tdPersonas = tdPersonas;
	}

	public Set getTdPuntos() {
		return this.tdPuntos;
	}

	public void setTdPuntos(Set tdPuntos) {
		this.tdPuntos = tdPuntos;
	}

	public Set getTdCompras() {
		return this.tdCompras;
	}

	public void setTdCompras(Set tdCompras) {
		this.tdCompras = tdCompras;
	}

}
