package com.rem.spring.entity;
// Generated 26-jul-2017 14:25:36 by Hibernate Tools 5.2.3.Final
import java.io.Serializable;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
/**
 * Producto generated by hbm2java
 */
@Entity
public class Producto implements Serializable {
	
	@Id
	@GeneratedValue
	private Integer id;
	private String pronom;
	private boolean proest;
	private double propre;
	private double stock;
	private String imagenUrl;
	private String descripcion;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="categoria_producto_id")
	private CategoriaProducto categoria;
	
	@OneToMany(mappedBy="producto", cascade=CascadeType.ALL)
	private List<DetalleCompra> detalleCompras;

	

	public Producto() {
	}

	public Producto(Integer id, String pronom, boolean proest, double propre, double stock, String imagenUrl,
			String descripcion) {
		super();
		this.id = id;
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
		this.stock = stock;
		this.imagenUrl = imagenUrl;
		this.descripcion = descripcion;
		
	}
	
	public Producto( String pronom, boolean proest, double propre, double stock, String imagenUrl,
			String descripcion) {
		super();
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
		this.stock = stock;
		this.imagenUrl = imagenUrl;
		this.descripcion = descripcion;
		
	}


	public Producto(Integer id, String pronom, boolean proest, double propre, double stock, String descripcion) {
		super();
		this.id = id;
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
		this.stock = stock;
		this.descripcion = descripcion;
	}

	public Producto(Integer id, String pronom, boolean proest, double propre, double stock, String imagenUrl,
			String descripcion, CategoriaProducto categoria) {
		super();
		this.id = id;
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
		this.stock = stock;
		this.imagenUrl = imagenUrl;
		this.descripcion = descripcion;
		this.categoria = categoria;
	}
	
	

	public Producto(Integer id, String pronom, boolean proest, double propre, double stock, String imagenUrl,
			CategoriaProducto categoria) {
		super();
		this.id = id;
		this.pronom = pronom;
		this.proest = proest;
		this.propre = propre;
		this.stock = stock;
		this.imagenUrl = imagenUrl;
		this.categoria = categoria;
	}



	@Override
	public String toString() {
		return "Producto [id=" + id + ", pronom=" + pronom + ", proest=" + proest + ", propre=" + propre + ", stock="
				+ stock + ", imagenUrl=" + imagenUrl + ", descripcion=" + descripcion + ", categoria=" + categoria
				+ ", detalleCompras=" + detalleCompras + "]";
	}



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPronom() {
		return pronom;
	}

	public void setPronom(String pronom) {
		this.pronom = pronom;
	}

	public boolean isProest() {
		return proest;
	}

	public void setProest(boolean proest) {
		this.proest = proest;
	}

	public double getPropre() {
		return propre;
	}

	public void setPropre(double propre) {
		this.propre = propre;
	}

	public double getStock() {
		return stock;
	}

	public void setStock(double stock) {
		this.stock = stock;
	}

	public String getImagenUrl() {
		return imagenUrl;
	}

	public void setImagenUrl(String imagenUrl) {
		this.imagenUrl = imagenUrl;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public CategoriaProducto getCategoria() {
		return categoria;
	}

	public void setCategoria(CategoriaProducto categoria) {
		this.categoria = categoria;
	}

	public List<DetalleCompra> getDetalleCompras() {
		return detalleCompras;
	}

	public void setDetalleCompras(List<DetalleCompra> detalleCompras) {
		this.detalleCompras = detalleCompras;
	}



}
