package com.rem.spring.entity;
// Generated 26-jul-2017 14:25:36 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import java.io.Serializable;
/**
 * Punto generated by hbm2java
 */
@Entity
public class Punto implements Serializable {
	
	@Id
	@GeneratedValue
	private Integer id;
	private BigDecimal puntos;
	
	@OneToOne(cascade= {CascadeType.ALL})
	@JoinColumn(name="td_cuenta_id")
	private Usuario tdCuentaId;

	
	public Punto() {
	}

	public Punto(Integer id, BigDecimal puntos, Usuario tdCuentaId) {
		super();
		this.id = id;
		this.puntos = puntos;
		this.tdCuentaId = tdCuentaId;
	}

	public Punto(Integer id, Usuario tdCuentaId) {
		super();
		this.id = id;
		this.tdCuentaId = tdCuentaId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BigDecimal getPuntos() {
		return puntos;
	}

	public void setPuntos(BigDecimal puntos) {
		this.puntos = puntos;
	}

	public Usuario getTdCuentaId() {
		return tdCuentaId;
	}

	public void setTdCuentaId(Usuario tdCuentaId) {
		this.tdCuentaId = tdCuentaId;
	}


}
