package com.rem.spring.entity;

// Generated 26-jul-2017 14:25:36 by Hibernate Tools 5.2.3.Final
import java.io.Serializable;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * Rol generated by hbm2java
 */
@Entity
public class Rol implements Serializable {

	@Id
	@GeneratedValue
	private Integer id;
	private String nombre;
	private boolean estado;
	
	@ManyToOne(cascade= {CascadeType.ALL})
	@JoinColumn(name = "usuario_id")
	private Usuario usuario;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Rol() {
	}

	public Rol(String nombre, boolean estado, Integer id) {
		this.nombre = nombre;
		this.estado = estado;
		this.id = id;
	}



}
