package com.rem.spring.entity;
// Generated 26-jul-2017 14:25:36 by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements Serializable {
	@Id
	@GeneratedValue
	@Column(name = "id")
	private Integer id;

	@Column(name = "nombreUsuario")
	private String nombreUsuario;

	@Column(name = "contrasenia")
	private String contrasenia;

	@Column(name = "estado")
	private boolean estado;

	@Column(name = "cuecorele")
	private String cuecorele;

	@OneToMany(mappedBy = "usuario", fetch = FetchType.EAGER)
	private Set<Rol> rol;

	@OneToOne(mappedBy = "usuario", fetch = FetchType.LAZY)
	private Persona persona;

	@OneToOne(mappedBy = "tdCuentaId", fetch = FetchType.LAZY)
	private Punto punto;

	@OneToMany(mappedBy = "usuario", fetch = FetchType.LAZY)
	private List<Compra> compra;

	public Usuario() {

	}

	public Usuario(Integer id, String nombreUsuario, String contrasenia, boolean estado, String cuecorele) {
		super();
		this.id = id;
		this.nombreUsuario = nombreUsuario;
		this.contrasenia = contrasenia;
		this.estado = estado;
		this.cuecorele = cuecorele;
	}

	public Usuario(Integer id, String nombreUsuario, String contrasenia, boolean estado) {
		super();
		this.id = id;
		this.nombreUsuario = nombreUsuario;
		this.contrasenia = contrasenia;
		this.estado = estado;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreUsuario() {
		return nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getContrasenia() {
		return contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public boolean isEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public String getCuecorele() {
		return cuecorele;
	}

	public void setCuecorele(String cuecorele) {
		this.cuecorele = cuecorele;
	}

	public Set<Rol> getRol() {
		return rol;
	}

	public void setRol(Set<Rol> rol) {
		this.rol = rol;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Punto getPunto() {
		return punto;
	}

	public void setPunto(Punto punto) {
		this.punto = punto;
	}

	public List<Compra> getCompra() {
		return compra;
	}

	public void setCompra(List<Compra> compra) {
		this.compra = compra;
	}
	
	

}
